name: Experimental Media, 2015
baseurl: /ExperimentalMedia2015
url: https://bakercp.github.io/ExperimentalMedia2015
description: ATS 5010, Fridays 1:00 PM - 4:00 PM
timezone: America/Chicago
gems:
    - jekyll-sitemap
